public enum Parameter
{
    NONE = -1,
    SWAY_PATH_TOTAL = 0,
    SWAY_PATH_AP = 1,
    SWAY_PATH_ML = 2,
    MEAN_SWAY_VELOCITY_TOTAL = 3,
    MEAN_SWAY_VELOCITY_AP = 4,
    MEAN_SWAY_VELOCITY_ML = 5,
    SWAY_AVERAGE_AMPLITUDE_AP = 6,
    SWAY_AVERAGE_AMPLITUDE_ML = 7,
    SWAY_MAXIMAL_AMPLITUDE_AP = 8,
    SWAY_MAXIMAL_AMPLITUDE_ML = 9,
    MEAN_DISTANCE = 10,
    ELLIPSE_AREA = 11
}
